### ISSUE TITLE
Is there a placeholder property?

### ISSUE THREAD

**Issue by ahmedsu** [react-native-community/datetimepicker#164]
# Question

Is there an option for a **placeholder**? Instead of showing default value, we should be able to show something like _dd/mm/yyyy_ which means the date is empty and you need to fill it.

**Comment by vonovak** [comment]
hello and thanks for the question. We do not provide such component because this out of the scope of this library. We provide functionality from UIDatePicker on iOS and DatePickerDialog + TimePickerDialog on Android.

see this note: https://github.com/react-native-community/datetimepicker#props

However, you can build such component yourself. Thanks!
