### ISSUE TITLE
Why doesn't the modal time window appear when a state changes in the React Native Debugger?

### ISSUE THREAD

**Issue by component6** [react-native-community/datetimepicker#85]
I change the state of the variable isDateTimePickerVisible (the type of the variable is boolen) in the React Native Debugger from true to false, and then:
1) <Text> isDateTimePickerVisible = true </Text> is displayed and hidden depending on the variable isDateTimePickerVisible
2) the modal time selection window does not appear. Why?

![FireShot Capture 063](https://user-images.githubusercontent.com/9214873/72247637-bf96e200-360e-11ea-9ba1-1fab63139f0a.png)
![FireShot Capture 064](https://user-images.githubusercontent.com/9214873/72247652-c7568680-360e-11ea-9ac6-64975cae0b30.png)

```
render() {
  const { isDateTimePickerVisible } = this.state;
  console.log('render => isDateTimePickerVisible: ', isDateTimePickerVisible);
  ... 
  {isDateTimePickerVisible && <Text>isDateTimePickerVisible = true</Text>}
  ... 
  {isDateTimePickerVisible && (
    <DateTimePicker
      mode="time"
      is24Hour={true}
      display="default"
      value={new Date()}
      // onChange={this.setDateTimePicker}
    />
  )}
  ... 
}
```

package.json
```
"dependencies": {
    "@react-native-community/datetimepicker": "^2.1.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
}
```

**Comment by ketan1062** [comment]
Same issue occurs. It works fine some days before after that automatically stops working. Please help me.

**Comment by davidbaussart** [comment]
hey, I've just encountered a similar issue, try to set a background color for the parent element.

I think the newly introduced iOS dark theme is setting the colors of the picker to white. In my case, the picker was completely white because I use dark theme, therefore not visible in my app (white picker on white background).
![Capture d’écran   2020-01-23 à 13 43 37](https://user-images.githubusercontent.com/25220066/72985688-cbd92700-3de6-11ea-8e1b-ecdf59e48151.jpeg)
![IMG_3820](https://user-images.githubusercontent.com/25220066/72985690-cc71bd80-3de6-11ea-870b-79bab337c48f.PNG)

**Comment by arsimr16** [comment]
https://github.com/react-native-community/datetimepicker#textcolor-optional-ios-only

**Comment by vonovak** [comment]
hello, I'm going to close this because I'm not sure if this is an android or ios issue, and the background color as well as text color on ios can be changed.

Please open a new issue if the problem persists.
